### ISSUE TITLE
Hubs/Routers do not wire up at all.

### ISSUE THREAD

**Issue by Rockdtben** [Nadrew/console#10]
Wiring hubs results in no wiring.

**Comment by Nadrew** [comment]
Can you elaborate a bit on what your fix did? It's kind of buried in here. I'm just curious how it decided to break on its own, likely something on BYOND's end that changed since it's in code that hasn't been touched in a super long time.

**Comment by Rockdtben** [comment]
code/hardware/hub.dm

**Comment by Rockdtben** [comment]
https://github.com/Nadrew/console/commit/03b152807b823b77f75aa91546b29d6f9aba2329#diff-70debad7a00e40a2c748dce7fc3d9a50

To fix the Routers and Hubs.


I just copied the code from the switchboard and removed the extra lines.

**Comment by Nadrew** [comment]
What I'm curious about is why they used to work and then stopped. Ah well.
