### ISSUE TITLE
Can't use mouse on map

### ISSUE THREAD

**Issue by swallis21** [Nadrew/console#2]
For whatever reason, hovering over the map in the game doesn't show the name of whatever your mouse is on top of. You can't left or right click on items in the map, though you can do so just fine in your inventory. This obviously breaks some fundamental features, like wiring and disks, since you can't click on computers to wire them or insert a disk. Is my client misconfigured or something?

**Comment by DarkChowder** [comment]
The zoom functionality is blocking the map. For some reason, setting mouse opacity to 0 isn’t working.
